### PR TITLE
Fix global iteration space bug in CUDA backend

### LINKED ISSUE #865: Fix global iteration space bug in CUDA backend
The current implementation of global indices in the Dawn CUDA backend does not copy the iteration space indices and global offsets to device memory before launching the kernel.

### PR DESCRIPTION
**Pull request by eddie-c-davis**
## Technical Description

This PR modifies the CudaCodeGen backend to copy global indices and offsets to device memory before the kernel call and frees it afterward.

### Resolves / Enhances

Resolves #865

### CODE REVIEW

**Comment by eddie-c-davis** [comment]
launch jenkins

**Comment by eddie-c-davis** [comment]
launch jenkins

File: dawn/src/dawn/CodeGen/Cuda/MSCodeGen.cpp [hunk 1]
```diff
@@ -1059,15 +1055,13 @@ void MSCodeGen::generateCudaKernelCode() {
           std::string iterators = "IJ";
           for(const auto& stage : iterateIIROver<iir::Stage>(*(stencilInstantiation_->getIIR()))) {
             std::string prefix = "stage" + std::to_string(stage->getStageID()) + "Global";
-            int index = 0;
-            for(const auto& interval : stage->getIterationSpace()) {
+            for(auto [index, interval] : enumerate(stage->getIterationSpace())) {
```
Comment (twicki) [inline dawn/src/dawn/CodeGen/Cuda/MSCodeGen.cpp]: I am torn if this is more or less readable than the standard `for(int i=0; i< size;++i)`
it is of course fancier and it's nice that c++ offers a way to get indices from range base loops. Is there an an advantage to this or do you think it's just the nicer way of doing things?

Comment (eddie-c-davis) [reply dawn/src/dawn/CodeGen/Cuda/MSCodeGen.cpp]: Johann has encouraged me to use these modern iterators, I personally have no strong preference. I am happy to change to standard C++ loops if you like.
