### PR TITLE
fixed sir::value class

### LINKED ISSUE #256: Strange Behavior of SIR::Value
While working on [PR236](https://github.com/MeteoSwiss-APN/dawn/pull/236) I noticed some strange behavior of the SIR::Value class, outlined in the following code sample:

```
  dawn::sir::Value test, test2;
  test.setType(dawn::sir::Value::TypeKind::Integer);
  test.setValue(12.); //silently switches type
  printf("value has type %s\n", 
    test.getType() == dawn::sir::Value::TypeKind::Integer ? "Integer" : "Double");  //prints "Double"

  //this would mean an assertion failure,  even though type was set to integer
  //int ret_val = test.getValue<int>();  

  // so lets try to correct the type to what we want (int)
  //    this sets test into an inconsitent state
  test.setType(dawn::sir::Value::TypeKind::Integer);
  printf("value is %s\n", test.toString().c_str()); // prints 0

  //this is not just an issue of toString()
  int ret_val = test.getValue<int>();
  printf("value stored is in fact: %d\n", ret_val); // still prints 0
```

This is the root cause of some (de)serialzation bugs addressed in the PR.

### PR DESCRIPTION
**Pull request by mroethlin**
## Technical Description

This fixes the issues about the problematic behavior of SIR::Value.

#### Resolves

resolves #256 

#### Dependencies

This PR is independent.

### CODE REVIEW

**Comment by mroethlin** [comment]
launch jenkins

File: src/dawn/SIR/SIR.h [hunk 1]
```diff
@@ -348,9 +361,47 @@ struct Value : NonCopyable {
...
+  }
+
+  template <class T>
+  typename std::enable_if<std::is_arithmetic<T>::value>::type
+  setValue(const T& value) {
+    if (type_ == TypeKind::None) {
+      valueImpl_ = make_unique<ValueImpl<T>>(value);
+      type_ = TypeInfo<T>::Type;
+    } else {
+      if (isArithmetic()) {
```
Comment (lukasm91) [inline src/dawn/SIR/SIR.h]: Do we need this check? You replicate isArithmetic in the switch case, the default is unreachable, but then there is an else, which would be equivalent.

File: src/dawn/SIR/SIR.h [hunk 2]
```diff
@@ -348,9 +361,47 @@ struct Value : NonCopyable {
...
+    }
+  }
+
+  template <class T>
+  typename std::enable_if<std::is_arithmetic<T>::value>::type
+  setValue(const T& value) {
+    if (type_ == TypeKind::None) {
+      valueImpl_ = make_unique<ValueImpl<T>>(value);
+      type_ = TypeInfo<T>::Type;
+    } else {
```
Comment (lukasm91) [inline src/dawn/SIR/SIR.h]: `elseif`

File: src/dawn/SIR/SIR.h [hunk 3]
```diff
@@ -348,9 +361,47 @@ struct Value : NonCopyable {
...
+            valueImpl_ = make_unique<ValueImpl<int>>((int) value);
+            break;
+          case Value::Boolean:
+            valueImpl_ = make_unique<ValueImpl<bool>>((bool) value);
+            break;
+          case Value::Double:
+            valueImpl_ = make_unique<ValueImpl<double>>((double) value);
+            break;
+          default:
+            DAWN_ASSERT(false); //unreachable
```
Comment (lukasm91) [inline src/dawn/SIR/SIR.h]: `dawn_unreachable`?

File: src/dawn/SIR/SIR.h [hunk 4]
```diff
@@ -348,9 +361,47 @@ struct Value : NonCopyable {
...
+        valueImpl_ = make_unique<ValueImpl<T>>(value);
+      } else {
+        //type mismatch
+        DAWN_ASSERT_MSG(false, "type mismatch trying to set sir::Value");
+      }
+    }
+  }
+
+  template <class T>
+  typename std::enable_if<std::is_arithmetic<T>::value>::type
```
Comment (lukasm91) [inline src/dawn/SIR/SIR.h]: Why two overloads? Might we be able to set the value if the type is constructible from T?

File: src/dawn/SIR/SIR.h [hunk 5]
```diff
@@ -348,9 +361,47 @@ struct Value : NonCopyable {
...
   template <class T>
-  void setValue(const T& value) {
-    valueImpl_ = make_unique<ValueImpl<T>>(value);
-    type_ = TypeInfo<T>::Type;
+  typename std::enable_if<!std::is_arithmetic<T>::value>::type
+  setValue(const T& value) {
+    if (type_ == TypeKind::None) {
+      valueImpl_ = make_unique<ValueImpl<T>>(value);
+      type_ = TypeInfo<T>::Type;
+    } else {
```
Comment (lukasm91) [inline src/dawn/SIR/SIR.h]: `else if`

File: src/dawn/SIR/SIR.h [hunk 6]
```diff
@@ -348,9 +361,47 @@ struct Value : NonCopyable {
...
+      if (TypeInfo<T>::Type == type_) {
```
Comment (lukasm91) [inline src/dawn/SIR/SIR.h]: So for non-arithmetic types, the behaviour is different and T actually needs to be the same as `type`. For arithmetic it only needs to be convertible. This is inconsistent.

File: src/dawn/SIR/SIR.h [hunk 7]
```diff
@@ -330,12 +330,25 @@ struct Value : NonCopyable {
...
+  bool isArithmetic() const;
+
   /// @brief Check if value is empty
   bool empty() const { return valueImpl_ == nullptr; }
 
   /// @brief Get/Set the underlying type
   TypeKind getType() const { return type_; }
-  void setType(TypeKind type) { type_ = type; }
+  void setType(TypeKind type) {
+    if (type_ == type) {
```
Comment (lukasm91) [inline src/dawn/SIR/SIR.h]: This first if is redundant and can be moved into else.
```
if (type_ == TypeKind::None)
    type_ = type;
else
    DAWN_ASSERT_MSG(type_ == type, "...");
```

**Comment by lukasm91** [comment]
Check in the description how you can link to an issue and tell github that it automatically closes it if the PR is merged.

**Comment by mroethlin** [comment]
As discussed, sir::Value is now an immutable class

**Comment by mroethlin** [comment]
launch jenkins

File: src/dawn/SIR/SIR.h [hunk 8]
```diff
@@ -371,6 +368,12 @@ struct Value : NonCopyable {
   }
 
 private:
+  template <class T>
+  void setValue(const T& value) {
+    valueImpl_ = make_unique<ValueImpl<T>>(value);
+    type_ = TypeInfo<T>::Type;
```
Comment (lukasm91) [inline src/dawn/SIR/SIR.h]: you can also completely remove `type_`: Add a member to `ValueImpl` and its base (getType) which returns `TypeInfo<T>::Type` in the implementation.

File: src/dawn/SIR/SIR.h [hunk 9]
```diff
@@ -314,9 +314,14 @@ struct Value : NonCopyable {
 
   template <class T>
   explicit Value(T&& value) : isConstexpr_(false) {
+    //TODO
+    //  I get a compiler error I don't understand when not using this redirection
```
Comment (lukasm91) [inline src/dawn/SIR/SIR.h]: I assume, in the end you will only have 
```
... : valueImpl(std::forward<T>(value)) {}
```
And the samme inside ValueImpl (and you can remove the pointer in ValueImpl). Maybe, this solves your compilre error too.

File: src/dawn/SIR/SIR.h [hunk 10]
```diff
@@ -314,9 +314,14 @@ struct Value : NonCopyable {
```
Comment (lukasm91) [inline src/dawn/SIR/SIR.h]: Is the default constructor needed (and related `TypeKind::None`)? I am wondering how this would be used, because it complicates the implementation of Value and any user of Value (because they all need to scope with the possibility that Value might be nothing), e.g. CodeGen.cpp, Line 67.

File: src/dawn/SIR/SIR.h [hunk 11]
```diff
@@ -346,13 +350,6 @@ struct Value : NonCopyable {
...
   }
 
-  /// @brief Set the value
-  template <class T>
-  void setValue(const T& value) {
-    valueImpl_ = make_unique<ValueImpl<T>>(value);
-    type_ = TypeInfo<T>::Type;
-  }
-
   struct EmptyType {};
```
Comment (lukasm91) [inline src/dawn/SIR/SIR.h]: Unused

File: src/dawn/SIR/SIR.h (hunk 9 above)
Comment (mroethlin) [reply src/dawn/SIR/SIR.h]: Unfortunately valueImp_ has to be a pointer, see below

File: src/dawn/SIR/SIR.h (hunk 10 above)
Comment (mroethlin) [reply src/dawn/SIR/SIR.h]: The default constructor is not needed and neither is `TypeKind::None`. What is needed is the `empyt()` method for things like `bool foo`, i.e. variables with a type but no value. However, in this case I believe that `empty()` is a bad name for the method at hand and I opted to rename it to `has_value()`

File: src/dawn/SIR/SIR.h (hunk 9 above)
Comment (lukasm91) [reply src/dawn/SIR/SIR.h]: Not the pointer to valueImpl (that's clear), but the pointer in valueImpl (ValuePtr)

File: src/dawn/SIR/SIR.h (hunk 10 above)
Comment (lukasm91) [reply src/dawn/SIR/SIR.h]: What's the reason for an empty Value? Respectively, how can a type have an empty set of possible values?

**Comment by mroethlin** [comment]
launch jenkins

File: src/dawn/SIR/SIR.h [hunk 12]
```diff
@@ -282,11 +282,17 @@ struct Value : NonCopyable {
   template <class T>
   explicit Value(T value) : isConstexpr_(false) {
     valueImpl_ = make_unique<ValueImpl<T>>(value);
+    //NOTE: perfect forwarding in this case can be achieved by using 
+    //explicit Value(T value) : isConstexpr_(false) {make_unique<ValueImpl<std::decay_t<T>>>(std::forward<T>(value));}
```
Comment (havogt) [inline src/dawn/SIR/SIR.h]: `typename std::decay<T>::type` or is there something else I am missing which doesn't work in c++11?
