### PR TITLE
Fixed two bugs in codegen, one related to intervals, one to max_over (#1097 and #1098)

### LINKED ISSUE #1097: Translation of max_over doesn't work
SIRs that contain this:
```
"reductionOverNeighborExpr": {
                                              "op": "max",
                                              ...
```
get wrongly translated to something like:
```
lhs_49 max = <RHS>;
```
instead of
```
lhs_49 = max(lhs_49, <RHS>);
```
in cuda-ico backend.
Same problem if instead of "op": "max" one uses "gridtools::dawn::math::max" (used for max outside of reductions).
This problem makes translation of the `max_over` Dusk syntax incorrect.

### LINKED ISSUE #1098: Cuda-ico vertical interval wrong generation
If one specifies this vertical interval in SIR:
```
"interval": {
                      "specialLowerLevel": "End",
                      "specialUpperLevel": "End",
                      "lowerOffset": -1
                    },
```
(`with domain.upwards[-1:]` in Dusk)
cuda-ico generates the following wrong translation:
```
int klo = kidx * LEVELS_PER_THREAD + 1048575;
int khi = (kidx + 1) * LEVELS_PER_THREAD + 1048575;
```
instead of
```
int klo = kidx * LEVELS_PER_THREAD + (kSize-1);
int khi = (kidx + 1) * LEVELS_PER_THREAD + (kSize-1);
```

### PR DESCRIPTION
**Pull request by muellch**
## Technical Description

Fixes the bugs in the following two tasks:
Fixes #1097 : Now explicitly check if the `lowerLevel` and `upperLevel` of the interval are both `End`.
Fixes #1098 : Now branch with `sum_over` being the special case and `max_over`, `min_over` behaving the same way.

### CODE REVIEW

**Comment by muellch** [comment]
launch jenkins

File: dawn/src/dawn/CodeGen/CXXNaive-ico/ASTStencilBody.cpp [hunk 1]
```diff
@@ -376,15 +376,22 @@ void ASTStencilBody::visit(const std::shared_ptr<ast::ReductionOverNeighborExpr>
...
         << ", auto const& weight) mutable {\n";
-    ss_ << "lhs " << expr->getOp() << "= ";
-    ss_ << "weight * ";
   } else {
     ss_ << ", [&, " + ASTStencilBody::ReductionSparseIndexVarName(reductionDepth_) +
                " = int(0)](auto& lhs, auto "
         << ASTStencilBody::ReductionIndexVarName(reductionDepth_ + 1) << ") mutable { ";
+  }
+
+  if(expr->getOp() != "+") {
```
Comment (mroethlin) [inline dawn/src/dawn/CodeGen/CXXNaive-ico/ASTStencilBody.cpp:385]: I don't think this is safe. There are other compound assignments (e.g. `-=`)

File: dawn/src/dawn/CodeGen/Cuda-ico/ASTStencilBody.cpp [hunk 2]
```diff
@@ -240,11 +240,18 @@ void ASTStencilBody::visit(const std::shared_ptr<ast::ReductionOverNeighborExpr>
       << "pidx * " << chainToSparseSizeString(expr->getIterSpace()) << " + nbhIter"
       << "];\n";
   ss_ << "if (nbhIdx == DEVICE_MISSING_VALUE) { continue; }";
-  ss_ << lhs_name << " " << expr->getOp() << "=";
+  if(expr->getOp() != "+") {
```
Comment (mroethlin) [inline dawn/src/dawn/CodeGen/Cuda-ico/ASTStencilBody.cpp:243]: c.f. above

**Review by mroethlin — CHANGES_REQUESTED** [review]
also consider other compound assignments, then we're good to go

File: dawn/src/dawn/CodeGen/CXXNaive-ico/ASTStencilBody.cpp (hunk 1 above)
Comment (muellch) [reply dawn/src/dawn/CodeGen/CXXNaive-ico/ASTStencilBody.cpp:385]: I thought at the moment there is only `sum_over`, `max_over` and `min_over`?
In that context `ReductionOverNeighborExpr` it should only be these 3.

I guess I could try to make it more future proof?
Would it be good enough if I excluse `+`, `-`, `*`, `/` and `%`?

Comment (mroethlin) [reply dawn/src/dawn/CodeGen/CXXNaive-ico/ASTStencilBody.cpp:385]: `sum_over`, `max_over` and `min_over` are the shortcuts available in dusk. there is also a more general `reduce_over` which takes an Operator as third argument. I'm currently not sure we ever formally specified which operators are allowed for the reduction concept. Your selection seems fine to me

**Comment by muellch** [comment]
launch jenkins

**Comment by muellch** [comment]
launch jenkins

**Comment by muellch** [comment]
launch jenkins

**Comment by muellch** [comment]
Alright, should be good now. After dealing with the arithmetic ops I did some cleanup.

**Review by mroethlin — APPROVED** [review]
I know we aren't very consistent with this, but dawn is supposed to use `camelCase` internally (but may emit `snake_case` code). Other than that it's good to go!

**Comment by muellch** [comment]
launch jenkins
