### PR TITLE
Allocate Temp Fields in the ICO Backends

### LINKED ISSUE #1043: Properly Handle Temporary Fields in Backends
The CudaIco Backend adds Temporaries to the API, making allocation of them a responsibility of the driver. The CXXIcoNaive backend simply ignores the issue altogether, guaranteeing a segfault for stencils with temporary fields. For this Issue: make the backends properly allocate temporary fields!

### PR DESCRIPTION
**Pull request by mroethlin**
## Technical Description

Fields that were introduced by the dawn tool chain (e.g. due to versioning) were poorly supported, if at all. The C++ backend produced some spurious code assuming structured fields, and the cuda backend put the responsibility of allocating said fields on the driver code.

### Limitations

* The naive backend leaks the memory when allocating these fields. This is not a big issue because the naive backend holds a persistent copy of the inner stencil class, so if the stencil class is used as intended this doesn't lead to a increasing memory footprint with each execution of the stencil

* The cuda backend allocates and de-allocates the fields for each `_from_host` run, which deteriorates performance. 

### Resolves / Enhances

Fixes #1043 

### Testing

Currently not sure how to properly test this from within dawn. icondusk-e2e tests show that this is fine. 

### Dependencies

This PR is independent.

### CODE REVIEW

**Comment by mroethlin** [comment]
launch jenkins

**Comment by mroethlin** [comment]
launch jenkins

**Comment by mroethlin** [comment]
launch jenkins

File: dawn/src/dawn/CodeGen/Cuda-ico/CudaIcoCodeGen.cpp [hunk 1]
```diff
@@ -367,6 +367,39 @@ void CudaIcoCodeGen::generateRunFun(
...
+      }
+
+      bool isHorizontal = !dims.K();
+      std::string kSizeStr = (isHorizontal) ? "1" : "kSize_";
+
+      auto hdims = sir::dimension_cast<sir::UnstructuredFieldDimension const&>(
+          dims.getHorizontalFieldDimension());
+      if(hdims.isDense()) {
+        ctor.addStatement("::dawn::allocField(&" +
+                          stencil.getMetadata().getNameFromAccessID(accessID) + "_, mesh_." +
```
Comment (Stagno) [inline dawn/src/dawn/CodeGen/Cuda-ico/CudaIcoCodeGen.cpp:390]:
```suggestion
                          fname + "_, mesh_." +
```

File: dawn/src/dawn/CodeGen/Cuda-ico/CudaIcoCodeGen.cpp [hunk 2]
```diff
@@ -367,6 +367,39 @@ void CudaIcoCodeGen::generateRunFun(
...
+                          locToDenseSizeStringGpuMesh(hdims.getDenseLocationType()) + ", " +
+                          kSizeStr + ")");
+      } else {
+        ctor.addStatement("::dawn::allocField(&" + fname + "_, " + "mesh_." +
+                          locToDenseSizeStringGpuMesh(hdims.getNeighborChain()[0]) + ", " +
```
Comment (Stagno) [inline dawn/src/dawn/CodeGen/Cuda-ico/CudaIcoCodeGen.cpp:395]:
```suggestion
                          locToDenseSizeStringGpuMesh(hdims.getDenseLocationType()) + ", " +
```

File: dawn/src/interface/atlas_interface.hpp [hunk 3]
```diff
@@ -102,14 +111,28 @@ class Field {
 
   T* data() { return atlas_field_.data(); }
   const T* data() const { return atlas_field_.data(); }
+
   int numElements() const { return atlas_field_.shape(0) * atlas_field_.shape(1); }
+  std::tuple<size_t, size_t> getShape() const {
+    return std::make_tuple(atlas_field_.shape(0), atlas_field_.shape(1));
+  }
 
+  Field() : atlas_field_(atlas::array::make_view<T, 2>(*atlas::array::Array::create<T>(0, 0))){};
```
Comment (Stagno) [inline dawn/src/interface/atlas_interface.hpp:120]: Is an empty field ever needed?

File: dawn/src/interface/atlas_interface.hpp [hunk 4]
```diff
@@ -102,14 +111,28 @@ class Field {
...
 
 private:
   atlas::array::ArrayView<T, 2> atlas_field_;
 };
 
+template <typename T>
+Field<T> allocateFieldLike(atlasTag, const Field<T>& other) {
+  auto shape = other.getShape();
+  // leaky!
+  auto field = new atlas::Field("copy", atlas::array::DataType::real64(),
```
Comment (Stagno) [inline dawn/src/interface/atlas_interface.hpp:131]: I understand that we need to do this because we don't have a register (held by the stencil class) of the allocated fields (and also we don't have a class to represent an allocated field, but only views).
This shows the need for a restructuring of naive ico.

File: dawn/src/interface/atlas_interface.hpp (hunk 3 above)
Comment (Stagno) [inline dawn/src/interface/atlas_interface.hpp:120]: Is an empty field ever needed?

File: dawn/src/interface/atlas_interface.hpp (hunk 4 above)
Comment (Stagno) [inline dawn/src/interface/atlas_interface.hpp:131]: I understand that we need to do this because we don't have a register (held by the stencil class) of the allocated fields (and also we don't have a class to represent an allocated field, but only views).
This shows the need for a restructuring of naive ico.

**Review by Stagno — CHANGES_REQUESTED** [review]
I have some doubts about the naive one, but the cuda implementation looks fine to me. 

Both the limitations that you mention seem unavoidable for now.
To overcome the first one we would need to refactor the naive ico backend. The second one corresponds to an open design problem, i.e. when and how should the driver setup a stencil before executing it?

**Comment by mroethlin** [comment]
launch jenkins

**Comment by mroethlin** [comment]
launch jenkins

**Comment by mroethlin** [comment]
launch jenkins

**Review by Stagno — APPROVED** [review]

**Comment by mroethlin** [comment]
launch jenkins
